name = "animegarden"
main = "src/index.ts"
compatibility_date = "2023-03-22"

[triggers]
crons = [
  "*/5 0 * * *",
  "*/10 1 * * *",
]

[[d1_databases]]
binding = "database"
database_name = "animegarden"
database_id = "1d8d91fc-3bde-4898-9149-900a56f7d0c2"
